### ISSUE TITLE
tailwind 8.2 release - question

### ISSUE THREAD

**Issue by alpha2k-io** [NativeScript/tailwind#101]
QUESTIONS .... 
I know that there is a plan to include tailwind as part of the 8.2 release.  From community video from Nathan.

Is the intent to update theme or this repo for the inclusion?

If we move forward with this repo what would be involved to migrate for 8.2?

**Comment by rigor789** [comment]
The goal is to rewrite the `@nativescript/theme` using `@nativescript/tailwind` as the base - generating most of the utility classes via tailwind and then adding some pre-defined element styles.
