### ISSUE TITLE
Tailwind 3 Release 

### ISSUE THREAD

**Issue by pandabuilt** [NativeScript/tailwind#122]
I see that tailwind 3 was released and we upgraded our nx repo with it.  Works flawlessly with web, however, because you are depending on version 2 it causes a few issues.

I see that dependabot has a branch, but when I used the branch tag it caused more errors. 

https://github.com/NativeScript/tailwind/tree/dependabot/npm_and_yarn/tailwindcss-3.0.22

The actual error I get is from post-css loader Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
But almost certainly positive it's a mismatched object somewhere since Tailwind 3 is different.
```TypeError: Cannot read properties of undefined (reading 'config')    at getTailwindConfig ```

**Comment by rigor789** [comment]
Released `2.0.0-rc.1` - updated readme with latest instructions.

**Comment by pandabuilt** [comment]
@rigor789  Sorry, forgot to tag you. Also, thanks for the speedy merge!

**Comment by rigor789** [comment]
Only looks for in the app folder - but you can re-export the root one easily:

```js
const sharedConfig = require('../../tailwind.config')

module.exports = {
  ...sharedConfig,
  // overrides here
}
```

**Comment by pandabuilt** [comment]
@rigor789 The classes stopped working for me now.  I use the above code 

Keep in mind - I did update @tailwind screens to @tailwind variants but utilities also don't work and that did not change. 

Anything quick you can think of off the top of your head?

**Comment by pandabuilt** [comment]
For some reason, it was removed from package.json in the app - didn't realize it.  Got it.

Thank you!
