### ISSUE TITLE
Button text is getting cut off.

### ISSUE THREAD

**Issue by kakha13** [NativeScript/tailwind#131]
Working with Nativescritp Vue
Example:
`<Button class="mx-4 text-lg text-green-600 bg-white h-20 rounded-2xl" text="Play"/>`
y letter is not fully displayed on screen.
iOS: [Screenshot](https://ibb.co/Rb13mnY)

![image](https://user-images.githubusercontent.com/879060/158450974-915ded34-3e5d-403b-b29d-f680c224b87c.png)

**Comment by rigor789** [comment]
Try removing `h-20` - I think it may be the issue in this case... I usually do `px-4 py-2` or whatever looks good instead of hard limits on the height...

**Comment by kakha13** [comment]
> 

removed all classes but same result.
I had same problems for different paddings without tailwind. it is Button element problem. label works great
