### ISSUE TITLE
Tailwind only works if "app" folder exists

### ISSUE THREAD

**Issue by flipperlite** [NativeScript/tailwind#190]
I looked at [this issue](https://github.com/NativeScript/tailwind/issues/187) but I'm not sure if it's related. I had been trying to integrate Tailwind into my NS 8.6.x project with no luck. I think it's scanning a **hard-coded** "app" folder for TW CSS class references and only bundling what it finds. Any XML files that exist outside of the "app" folder are not scanned and bundled with the TW CSS. I have two identical projects except the code folder named "app" (working) and "src" (broken). I've also tried naming the folder "app2" and it fails too. You can actually have both folders but only classes found in the "app" folder will be available in the "src" TW references.

[WORKING demo](https://stackblitz.com/edit/nativescript-stackblitz-templates-uo22uv?file=package.json%3AL3&title=NativeScript%20Starter%20TypeScript) using "app" folder

[BROKEN demo](https://stackblitz.com/edit/nativescript-stackblitz-templates-dnbmgv?file=package.json%3AL3-L3) using "src" folder

If it is hard-coded, at least update the README.md to avoid future issues and headaches. Ideally, it's set to scan all folders for TW references.

BTW, the NS CLI creator puts code into the "src" folder, not the "app" folder which created my problem. E.g. `ns create new-project-ts --template @nativescript/template-drawer-navigation-ts`.

**Comment by rigor789** [comment]
The folder can differ between templates, you can change the `tailwind.config.js` to look for classes in any folder, the readme is an example using the `app` folder, but you are free to change that to wherever your files are.

![image](https://github.com/NativeScript/tailwind/assets/879060/a7cb0619-cca3-4d87-988e-a4734ad61a6b)
